// Ensures src/version.js is aligned; consider also updating service-worker.js during version bumps
#!/usr/bin/env node
/*
 Generates src/version.js from package.json version.
 Makes the version available to the browser as a named export and on window.
*/

const fs = require('fs');
const path = require('path');

function generateVersionModule() {
  const root = process.cwd();
  const pkgPath = path.join(root, 'package.json');
  const outDir = path.join(root, 'src');
  const outPath = path.join(outDir, 'version.js');

  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const version = pkg.version || '0.0.0-dev';

  const banner = '// This file is auto-generated by tools/generate-version.js\n';
  const content = `${banner}export const APP_VERSION = '${version}';\n` +
                  `try { if (typeof window !== 'undefined') window.APP_VERSION = APP_VERSION; } catch {}\n`;

  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outPath, content, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Wrote ${path.relative(root, outPath)} with version ${version}`);
}

try {
  generateVersionModule();
} catch (err) {
  // eslint-disable-next-line no-console
  console.error('Failed to generate version module:', err);
  process.exitCode = 1;
}


